chore: update packages to remove vulnerabilities
silvermine/fsaba pull request #3
Opened 2021-05-13 19:42 UTC by jimjenkins5

Note: There is still one "low" vulnerability in `mocha`. This vulnerability is fixed in a later version, but `grunt-mocha-phantomjs` is not compatible with later versions of `mocha`.

2021-05-19 15:10 UTC, yokuze requested changes
Just the one thing about single vs double quotes. Otherwise it looks good.

2021-05-19 15:10 UTC, yokuze commented on .travis.yml
> +   - '14'
I don't know if it matters, but this line and the next changed from double quotes to single quotes.

2021-05-26 12:38 UTC, jthomerson approved these changes

2021-05-26 12:38 UTC, merged

2021-05-26 12:39 UTC, jthomerson commented
I merged this, but @yokuze feel free to comment if you see anything else that needs to be addressed in a subsequent PR.

2021-05-26 12:45 UTC, jthomerson commented
Published in + fsaba@0.2.1

CC @jimjenkins5 @yokuze